### ISSUE TITLE
Consider benefiting from static analysis

### ISSUE THREAD

**Issue by szepeviktor** [imath/required-block-attributes#1]
Powered by @phpstan

```
composer require --dev szepeviktor/phpstan-wordpress
vendor/bin/phpstan analyze
```

`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - class-required-block-attributes.php
        - inc/
    autoload_files:
        - class-required-block-attributes.php
        - inc/admin.php
        - inc/functions.php
        - inc/globals.php
        - inc/registers.php
        - inc/example.php
```
